---
# tasks file for master_db

#- name: Get master binlog file name and binlog position
#  mysql_replication:
#    login_user: 'root'
#    login_password: '{{ db_root_pass }}'
#    mode: getmaster
#  register: master_state


#- name: Stop MySQL replica thread
#  community.mysql.mysql_replication:
#    mode: stopreplica
#  when: replica_state.Is_Slave == true
#
#- name: Reset all slaves
#  community.mysql.mysql_replication:
#    mode: resetreplicaall
#  when: replica_state.Is_Slave == true
